error: implement ExtendedError for main error type
Implement this type so that we can use it for scripting, which requires
an ExtendedError.

Signed-off-by: brian m. carlson <sandals@crustytoothpaste.net>